name 'install_util'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures install_util'
long_description 'Installs/Configures install_util'
version '0.1.0'
